"""empty message

Revision ID: 260768ec8f60
Revises: 2da3e2530a57
Create Date: 2023-02-04 18:39:54.675837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '260768ec8f60'
down_revision = '2da3e2530a57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
